import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from '@/components/header';
import BottomNav from '@/components/bottomNav';
import { CartProvider } from '@/context/cartContext';
import { WishlistProvider } from '@/context/wishListContext';
import { SessionProvider } from 'next-auth/react';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>

    
          <CartProvider>
            <WishlistProvider>
              <Header />
              <div className="py-12">{children}</div>
              <BottomNav />
            </WishlistProvider>
          </CartProvider>
          </SessionProvider>
      </body>
    </html>
  );
}
